// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: test.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace TestProto
{

    [global::ProtoBuf.ProtoContract()]
    public partial class TestClientToServer : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id")]
        public ulong Id { get; set; }

        [global::ProtoBuf.ProtoMember(101)]
        public Hello hello
        {
            get => __pbn__payload.Is(101) ? ((Hello)__pbn__payload.Object) : default;
            set => __pbn__payload = new global::ProtoBuf.DiscriminatedUnionObject(101, value);
        }
        public bool ShouldSerializehello() => __pbn__payload.Is(101);
        public void Resethello() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__payload, 101);

        private global::ProtoBuf.DiscriminatedUnionObject __pbn__payload;

        [global::ProtoBuf.ProtoMember(102)]
        public Goodbye goodbye
        {
            get => __pbn__payload.Is(102) ? ((Goodbye)__pbn__payload.Object) : default;
            set => __pbn__payload = new global::ProtoBuf.DiscriminatedUnionObject(102, value);
        }
        public bool ShouldSerializegoodbye() => __pbn__payload.Is(102);
        public void Resetgoodbye() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__payload, 102);

        public PayloadOneofCase PayloadCase => (PayloadOneofCase)__pbn__payload.Discriminator;

        public enum PayloadOneofCase
        {
            None = 0,
            hello = 101,
            goodbye = 102,
        }

        [global::ProtoBuf.ProtoContract()]
        public partial class Hello : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"query")]
            [global::System.ComponentModel.DefaultValue("")]
            public string Query { get; set; } = "";

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class Goodbye : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(2, Name = @"farewell")]
            [global::System.ComponentModel.DefaultValue("")]
            public string Farewell { get; set; } = "";

        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TestServerToClient : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id")]
        public ulong Id { get; set; }

        [global::ProtoBuf.ProtoMember(101, Name = @"show")]
        public ShowData Show
        {
            get => __pbn__payload.Is(101) ? ((ShowData)__pbn__payload.Object) : default;
            set => __pbn__payload = new global::ProtoBuf.DiscriminatedUnionObject(101, value);
        }
        public bool ShouldSerializeShow() => __pbn__payload.Is(101);
        public void ResetShow() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__payload, 101);

        private global::ProtoBuf.DiscriminatedUnionObject __pbn__payload;

        [global::ProtoBuf.ProtoMember(102, Name = @"hide")]
        public HideData Hide
        {
            get => __pbn__payload.Is(102) ? ((HideData)__pbn__payload.Object) : default;
            set => __pbn__payload = new global::ProtoBuf.DiscriminatedUnionObject(102, value);
        }
        public bool ShouldSerializeHide() => __pbn__payload.Is(102);
        public void ResetHide() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__payload, 102);

        public PayloadOneofCase PayloadCase => (PayloadOneofCase)__pbn__payload.Discriminator;

        public enum PayloadOneofCase
        {
            None = 0,
            Show = 101,
            Hide = 102,
        }

        [global::ProtoBuf.ProtoContract()]
        public partial class ShowData : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"data")]
            [global::System.ComponentModel.DefaultValue("")]
            public string Data { get; set; } = "";

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class HideData : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(2, Name = @"data")]
            [global::System.ComponentModel.DefaultValue("")]
            public string Data { get; set; } = "";

        }

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
