      - name: pull atcbuild
        run: echo $CR_PAT | docker login ghcr.io -u felix-b --password-stdin && docker pull ghcr.io/felix-b/atcbuild
        env:
          CR_PAT: ${{secrets.CR_PAT}}

      - name: print GITHUB_WORKSPACE
        run: echo "$GITHUB_WORKSPACE" && ls -la

      - name: run atcbuild
        run: docker run --rm -v ${GITHUB_WORKSPACE}:/src --user $(id -u):$(id -g) ghcr.io/felix-b/atcbuild lin win mac

      - name: create version.txt
        id: create_version_txt
        run: |
          echo "build # $GH_RUN_NUMBER" > assets/version.txt 
          echo "commit $GH_COMMIT_SHA" >> assets/version.txt
          echo "to $GH_REF" >> assets/version.txt
          if ["$GH_REF" != "refs/heads/master"]; then
            echo "*** this is a pull request build! ***" >> assets/version.txt
          fi
          echo "::set-output name=DATE_NOW::$(date)"
          echo $(date) >> assets/version.txt
        env:
          GH_RUN_NUMBER: ${{ github.run_number }}
          GH_COMMIT_SHA: ${{ github.sha }}
          GH_EVENT_NAME: ${{ github.event_name }}
          GH_REF: ${{ github.ref }}
          GH_HEAD_REF: ${{ github.head_ref }}

      - name: create zip artifact
        run: |
          mkdir -p assets/64
          cp build-lin/src/lin.xpl assets/64/
          cp build-mac/src/mac.xpl assets/64/
          cp build-win/src/win.xpl assets/64/
          mv assets airTrafficAndControl
          zip -r airTrafficAndControl airTrafficAndControl

      - name: upload zip artifact
        uses: actions/upload-artifact@v2
        with:
          name: airTrafficAndControl.zip
          path: airTrafficAndControl.zip

      - name: if master, find current nightly download
        if: github.ref == 'refs/heads/master'
        uses: octokit/request-action@v2.x
        id: get_old_release_asset
        with:
          route: GET /repos/:repository/releases/31521929/assets
          repository: ${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: if master, log found nightly download
        if: github.ref == 'refs/heads/master'
        run: echo "$ASSET_JSON"
        env:
          ASSET_JSON: ${{ steps.get_old_release_asset.outputs.data }}

      - name: if master, delete current nightly download
        if: github.ref == 'refs/heads/master'
        uses: octokit/request-action@v2.x
        with:
          route: DELETE /repos/:repository/releases/assets/:old_asset_id
          repository: ${{ github.repository }}
          old_asset_id: ${{ fromJson(steps.get_old_release_asset.outputs.data)[0].id }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: if master, publish new nightly download
        if: github.ref == 'refs/heads/master'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: 'https://uploads.github.com/repos/felix-b/atc/releases/31521929/assets?name=airTrafficControl.zip'
          asset_path: 'airTrafficAndControl.zip'
          asset_name: 'airTrafficAndControl.zip'
          asset_content_type: 'application/zip'

      - name: if master, update nightly release text
        if: github.ref == 'refs/heads/master'
        uses: octokit/request-action@v2.x
        with:
          route: PATCH /repos/:repository/releases/31521929
          repository: ${{ github.repository }}
          body: ${{ steps.create_version_txt.outputs.DATE_NOW }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
